apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: {{ .Values.serviceName }}-vs
  namespace: default
spec:
  gateways:
  - {{ .Values.gatewayName }}
  hosts:
  - '*'
  http:
  - match:
    - uri:
        prefix: {{ .Values.prefixPath }}
    rewrite:
      uri: /
    route:
    - destination:
        host: "{{ .Values.serviceName }}.{{ .Values.namespaceName }}.cluster.local"
        port:
          number: 80
      headers:
        request:
          add:
            x-forwarded-prefix: {{ .Values.prefixPath }}